export const PROFISSOES = [
  // Saúde
  { label: 'Médica', categoria: 'Saúde' },
  { label: 'Fisioterapeuta', categoria: 'Saúde' },
  { label: 'Enfermeira', categoria: 'Saúde' },
  { label: 'Técnica de Enfermagem', categoria: 'Saúde' },
  { label: 'Psicóloga', categoria: 'Saúde' },
  { label: 'Nutricionista', categoria: 'Saúde' },
  { label: 'Fonoaudióloga', categoria: 'Saúde' },
  { label: 'Terapeuta Ocupacional', categoria: 'Saúde' },
  { label: 'Dentista', categoria: 'Saúde' },
  { label: 'Cuidadora', categoria: 'Saúde' },
  { label: 'Doula', categoria: 'Saúde' },
  { label: 'Farmacêutica', categoria: 'Saúde' },
  { label: 'Biomédica', categoria: 'Saúde' },

  // Beleza & Estética
  { label: 'Cabeleireira', categoria: 'Beleza & Estética' },
  { label: 'Manicure', categoria: 'Beleza & Estética' },
  { label: 'Pedicure', categoria: 'Beleza & Estética' },
  { label: 'Maquiadora', categoria: 'Beleza & Estética' },
  { label: 'Designer de Sobrancelhas', categoria: 'Beleza & Estética' },
  { label: 'Esteticista', categoria: 'Beleza & Estética' },
  { label: 'Lash Designer', categoria: 'Beleza & Estética' },
  { label: 'Massoterapeuta', categoria: 'Beleza & Estética' },
  { label: 'Tatuadora', categoria: 'Beleza & Estética' },
  { label: 'Micropigmentadora', categoria: 'Beleza & Estética' },
  { label: 'Depiladora', categoria: 'Beleza & Estética' },
  { label: 'Trancista', categoria: 'Beleza & Estética' },
  { label: 'Visagista', categoria: 'Beleza & Estética' },

  // Arte & Criação
  { label: 'Fotógrafa', categoria: 'Arte & Criação' },
  { label: 'Videomaker', categoria: 'Arte & Criação' },
  { label: 'Ilustradora', categoria: 'Arte & Criação' },
  { label: 'Designer Gráfica', categoria: 'Arte & Criação' },
  { label: 'Artesã', categoria: 'Arte & Criação' },
  { label: 'Ceramista', categoria: 'Arte & Criação' },
  { label: 'Cantora', categoria: 'Arte & Criação' },
  { label: 'Musicista', categoria: 'Arte & Criação' },
  { label: 'DJ', categoria: 'Arte & Criação' },
  { label: 'Dançarina', categoria: 'Arte & Criação' },
  { label: 'Atriz', categoria: 'Arte & Criação' },

  // Eventos & Hospitalidade
  { label: 'Garçonete', categoria: 'Eventos & Hospitalidade' },
  { label: 'Recepcionista de Eventos', categoria: 'Eventos & Hospitalidade' },
  { label: 'Bartender', categoria: 'Eventos & Hospitalidade' },
  { label: 'Cozinheira', categoria: 'Eventos & Hospitalidade' },
  { label: 'Confeiteira', categoria: 'Eventos & Hospitalidade' },
  { label: 'Cake Designer', categoria: 'Eventos & Hospitalidade' },
  { label: 'Hostess', categoria: 'Eventos & Hospitalidade' },
  { label: 'Cerimonialista', categoria: 'Eventos & Hospitalidade' },
  { label: 'Decoradora de Festas', categoria: 'Eventos & Hospitalidade' },
  { label: 'Promotora de Eventos', categoria: 'Eventos & Hospitalidade' },
  { label: 'Auxiliar de Cozinha', categoria: 'Eventos & Hospitalidade' },

  // Casa & Cuidado
  { label: 'Diarista', categoria: 'Casa & Cuidado' },
  { label: 'Faxineira', categoria: 'Casa & Cuidado' },
  { label: 'Passadeira', categoria: 'Casa & Cuidado' },
  { label: 'Babá', categoria: 'Casa & Cuidado' },
  { label: 'Cuidadora de Idosos', categoria: 'Casa & Cuidado' },
  { label: 'Cozinheira Particular', categoria: 'Casa & Cuidado' },
  { label: 'Governanta', categoria: 'Casa & Cuidado' },
  { label: 'Dog Walker', categoria: 'Casa & Cuidado' },
  { label: 'Pet Sitter', categoria: 'Casa & Cuidado' },
  { label: 'Organizadora Residencial', categoria: 'Casa & Cuidado' },

  // Transporte
  { label: 'Motorista', categoria: 'Transporte' },
  { label: 'Motogirl', categoria: 'Transporte' },
  { label: 'Entregadora', categoria: 'Transporte' },
  { label: 'Motorista Particular', categoria: 'Transporte' },
  { label: 'Guia Acompanhante', categoria: 'Transporte' },

  // Educação
  { label: 'Professora', categoria: 'Educação' },
  { label: 'Pedagoga', categoria: 'Educação' },
  { label: 'Tutora', categoria: 'Educação' },
  { label: 'Professora de Idiomas', categoria: 'Educação' },
  { label: 'Professora de Reforço', categoria: 'Educação' },
  { label: 'Instrutora de Cursos', categoria: 'Educação' },
  { label: 'Professora de Música', categoria: 'Educação' },
  { label: 'Educadora Infantil', categoria: 'Educação' },
  { label: 'Mentora', categoria: 'Educação' },
  { label: 'Coach', categoria: 'Educação' },

  // Administrativo & Negócios
  { label: 'Secretária', categoria: 'Administrativo & Negócios' },
  { label: 'Assistente Virtual', categoria: 'Administrativo & Negócios' },
  { label: 'Atendente', categoria: 'Administrativo & Negócios' },
  { label: 'Vendedora', categoria: 'Administrativo & Negócios' },
  { label: 'Consultora Comercial', categoria: 'Administrativo & Negócios' },
  { label: 'Recrutadora', categoria: 'Administrativo & Negócios' },
  { label: 'Analista Administrativa', categoria: 'Administrativo & Negócios' },
  { label: 'Auxiliar Financeira', categoria: 'Administrativo & Negócios' },

  // Tecnologia & Digital
  { label: 'Programadora', categoria: 'Tecnologia & Digital' },
  { label: 'Desenvolvedora de Sites', categoria: 'Tecnologia & Digital' },
  { label: 'UX/UI Designer', categoria: 'Tecnologia & Digital' },
  { label: 'Social Media', categoria: 'Tecnologia & Digital' },
  { label: 'Gestora de Tráfego', categoria: 'Tecnologia & Digital' },
  { label: 'Redatora', categoria: 'Tecnologia & Digital' },
  { label: 'Copywriter', categoria: 'Tecnologia & Digital' },
  { label: 'Editora de Vídeo', categoria: 'Tecnologia & Digital' },
  { label: 'Criadora de Conteúdo', categoria: 'Tecnologia & Digital' },
  { label: 'Community Manager', categoria: 'Tecnologia & Digital' },
  { label: 'Analista de Dados', categoria: 'Tecnologia & Digital' },

  // Moda & Imagem
  { label: 'Costureira', categoria: 'Moda & Imagem' },
  { label: 'Estilista', categoria: 'Moda & Imagem' },
  { label: 'Personal Stylist', categoria: 'Moda & Imagem' },
  { label: 'Consultora de Imagem', categoria: 'Moda & Imagem' },
  { label: 'Modelo', categoria: 'Moda & Imagem' },
  { label: 'Personal Shopper', categoria: 'Moda & Imagem' },

  // Bem-estar & Esporte
  { label: 'Personal Trainer', categoria: 'Bem-estar & Esporte' },
  { label: 'Professora de Yoga', categoria: 'Bem-estar & Esporte' },
  { label: 'Professora de Pilates', categoria: 'Bem-estar & Esporte' },
  { label: 'Terapeuta Integrativa', categoria: 'Bem-estar & Esporte' },
  { label: 'Instrutora Funcional', categoria: 'Bem-estar & Esporte' },
  { label: 'Massagista Esportiva', categoria: 'Bem-estar & Esporte' },
  { label: 'Terapeuta Holística', categoria: 'Bem-estar & Esporte' },

  // Construção & Técnicos
  { label: 'Arquiteta', categoria: 'Construção & Técnicos' },
  { label: 'Engenheira', categoria: 'Construção & Técnicos' },
  { label: 'Designer de Interiores', categoria: 'Construção & Técnicos' },
  { label: 'Pintora', categoria: 'Construção & Técnicos' },
  { label: 'Eletricista', categoria: 'Construção & Técnicos' },
  { label: 'Marceneira', categoria: 'Construção & Técnicos' },

  // Jurídico
  { label: 'Advogada', categoria: 'Jurídico' },
  { label: 'Contadora', categoria: 'Jurídico' },
  { label: 'Corretora de Imóveis', categoria: 'Jurídico' },
  { label: 'Consultora Empresarial', categoria: 'Jurídico' },
  { label: 'Perita', categoria: 'Jurídico' },
]

export const CATEGORIAS = [
  'Saúde',
  'Beleza & Estética',
  'Arte & Criação',
  'Eventos & Hospitalidade',
  'Casa & Cuidado',
  'Transporte',
  'Educação',
  'Administrativo & Negócios',
  'Tecnologia & Digital',
  'Moda & Imagem',
  'Bem-estar & Esporte',
  'Construção & Técnicos',
  'Jurídico',
]

export const CIDADES_POR_ESTADO = {
  AC: ['Rio Branco, AC'],
  AL: ['Maceió, AL'],
  AM: ['Manaus, AM'],
  AP: ['Macapá, AP'],
  BA: ['Salvador, BA', 'Feira de Santana, BA', 'Vitória da Conquista, BA'],
  CE: ['Fortaleza, CE', 'Caucaia, CE'],
  DF: ['Brasília, DF'],
  ES: ['Vitória, ES', 'Vila Velha, ES', 'Serra, ES'],
  GO: ['Goiânia, GO', 'Anápolis, GO', 'Aparecida de Goiânia, GO'],
  MA: ['São Luís, MA', 'Imperatriz, MA'],
  MG: ['Belo Horizonte, MG', 'Contagem, MG', 'Uberlândia, MG', 'Juiz de Fora, MG', 'Montes Claros, MG', 'Uberaba, MG', 'Ribeirão Preto, MG', 'Governador Valadares, MG'],
  MS: ['Campo Grande, MS'],
  MT: ['Cuiabá, MT'],
  PA: ['Belém, PA', 'Santarém, PA'],
  PB: ['João Pessoa, PB', 'Campina Grande, PB'],
  PE: ['Recife, PE', 'Caruaru, PE', 'Olinda, PE'],
  PI: ['Teresina, PI'],
  PR: ['Curitiba, PR', 'Londrina, PR', 'Maringá, PR', 'Cascavel, PR', 'Ponta Grossa, PR', 'Foz do Iguaçu, PR'],
  RJ: ['Rio de Janeiro, RJ', 'Niterói, RJ', 'Nova Iguaçu, RJ', 'Duque de Caxias, RJ', 'Petrópolis, RJ', 'Volta Redonda, RJ'],
  RN: ['Natal, RN'],
  RO: ['Porto Velho, RO'],
  RR: ['Boa Vista, RR'],
  RS: ['Porto Alegre, RS', 'Caxias do Sul, RS', 'Pelotas, RS', 'Canoas, RS', 'Gravataí, RS'],
  SC: ['Florianópolis, SC', 'Joinville, SC', 'Blumenau, SC', 'São José, SC'],
  SE: ['Aracaju, SE'],
  SP: ['São Paulo, SP', 'Guarulhos, SP', 'Campinas, SP', 'São Bernardo do Campo, SP', 'Santo André, SP', 'Osasco, SP', 'Sorocaba, SP', 'Ribeirão Preto, SP', 'São José dos Campos, SP', 'Santos, SP', 'Mogi das Cruzes, SP', 'Jundiaí, SP', 'Piracicaba, SP', 'Bauru, SP', 'Barueri, SP', 'Diadema, SP', 'Carapicuíba, SP', 'Mauá, SP', 'Guarujá, SP', 'Franca, SP', 'São José do Rio Preto, SP', 'Limeira, SP'],
  TO: ['Palmas, TO'],
}

// Flat list of all cities (for backward compat)
export const CIDADES_BR = Object.values(CIDADES_POR_ESTADO).flat()

export const ESTADOS_BR = [
  { sigla: 'AC', nome: 'Acre' },
  { sigla: 'AL', nome: 'Alagoas' },
  { sigla: 'AM', nome: 'Amazonas' },
  { sigla: 'AP', nome: 'Amapá' },
  { sigla: 'BA', nome: 'Bahia' },
  { sigla: 'CE', nome: 'Ceará' },
  { sigla: 'DF', nome: 'Distrito Federal' },
  { sigla: 'ES', nome: 'Espírito Santo' },
  { sigla: 'GO', nome: 'Goiás' },
  { sigla: 'MA', nome: 'Maranhão' },
  { sigla: 'MG', nome: 'Minas Gerais' },
  { sigla: 'MS', nome: 'Mato Grosso do Sul' },
  { sigla: 'MT', nome: 'Mato Grosso' },
  { sigla: 'PA', nome: 'Pará' },
  { sigla: 'PB', nome: 'Paraíba' },
  { sigla: 'PE', nome: 'Pernambuco' },
  { sigla: 'PI', nome: 'Piauí' },
  { sigla: 'PR', nome: 'Paraná' },
  { sigla: 'RJ', nome: 'Rio de Janeiro' },
  { sigla: 'RN', nome: 'Rio Grande do Norte' },
  { sigla: 'RO', nome: 'Rondônia' },
  { sigla: 'RR', nome: 'Roraima' },
  { sigla: 'RS', nome: 'Rio Grande do Sul' },
  { sigla: 'SC', nome: 'Santa Catarina' },
  { sigla: 'SE', nome: 'Sergipe' },
  { sigla: 'SP', nome: 'São Paulo' },
  { sigla: 'TO', nome: 'Tocantins' },
]
